openapi: "3.1.3"
info:
  title: Football Video API
  version: "1.0.0"
  description: API for fetching football videos by categories and date ranges.
servers:
  - url: https://your-render-service.onrender.com/api

paths:
  /categories:
    get:
      summary: Get all video categories
      responses:
        "200":
          description: List of categories
          content:
            application/json:
              example:
                data:
                  - id: 1
                    name: All goals
                  - id: 2
                    name: Highlights

  /videos:
    get:
      summary: Get all videos
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Page number
        - in: query
          name: pageSize
          schema:
            type: integer
            default: 10
          description: Number of items per page
        - in: query
          name: sort
          schema:
            type: string
            enum: [ASC, DESC]
            default: DESC
          description: Sort order
      responses:
        '200':
          description: A list of all videos
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Video'

  /videos/category/{categoryName}:
    get:
      summary: Get videos by category
      parameters:
        - in: path
          name: categoryName
          required: true
          schema:
            type: string
          description: Category name
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: pageSize
          schema:
            type: integer
            default: 10
        - in: query
          name: sort
          schema:
            type: string
            enum: [ASC, DESC]
            default: DESC
      responses:
        '200':
          description: Videos by category
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Video'

  /videos/category/{categoryName}/date/{filter}:
    get:
      summary: Get videos by category and date filter
      parameters:
        - in: path
          name: categoryName
          required: true
          schema:
            type: string
        - in: path
          name: filter
          required: true
          schema:
            type: string
            enum: [yesterday, today, tomorrow]
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: pageSize
          schema:
            type: integer
            default: 10
        - in: query
          name: sort
          schema:
            type: string
            enum: [ASC, DESC]
            default: DESC
        - in: query
          name: tz
          schema:
            type: string
            default: Africa/Lagos
          description: Timezone for date filtering
      responses:
        '200':
          description: Videos by category and date filter
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Video'

  /videos/date:
    get:
      summary: Get videos by date range (optionally by category)
      parameters:
        - in: query
          name: from
          required: true
          schema:
            type: string
            format: date
        - in: query
          name: to
          required: true
          schema:
            type: string
            format: date
        - in: query
          name: category
          schema:
            type: string
          description: Optional category filter
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: pageSize
          schema:
            type: integer
            default: 10
        - in: query
          name: sort
          schema:
            type: string
            enum: [ASC, DESC]
            default: DESC
      responses:
        '200':
          description: Videos by date range
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Video'

  /videos/{id}:
    get:
      summary: Get a single video by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single video
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
        '404':
          description: Video not found

components:
  schemas:
    Video:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        url:
          type: string
        category:
          type: string
        created_at:
          type: string
          format: date-time